baseURL = 'https://bodenmoraski.github.io/'
languageCode = 'en-us'
title = 'Boden Moraski'
theme = 'bearcub'

# Enable features
enableGitInfo = false
enableEmoji = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

canonifyURLs = true

[params]
  description = "High school founder, writer, and researcher passionate about building tools that actually make people's lives better"
  
  [params.author]
    name = "Boden Moraski"
    email = "bodenmoraski@gmail.com"

[menu]
  [[menu.main]]
    identifier = "experience"
    name = "Experience"
    url = "/experience/"
    weight = 1
  [[menu.main]]
    identifier = "writing"
    name = "Writing"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3
  

